// AUTO-GENERATED by scripts/merge-xhs-auto-redbook-css.mjs — do not edit by hand

export const AUTO_REDBOOK_THEME_RAW: Record<string, string> = {
	"default": `/* ============================================
   Default - 默认风格
   小红书原生风格，渐变紫色背景
   适配小红书卡片渲染
   ============================================ */

/* 配色定义
   背景色: #FFFFFF (白色卡片)
   前景色: #475569 (中性灰)
   主色: #6366f1 (靛蓝紫)
   浅紫: #8b5cf6 (紫罗兰)
   灰色: #64748b (石板灰)
   边框: #e2e8f0 (浅灰边框)
*/

.mdtp-xhs-card-content {
  color: #475569;
  background-color: #ffffff;
  font-size: 42px;
  line-height: 1.7;
}

/* 标题样式 */
.mdtp-xhs-card-content h1 {
  font-size: 72px;
  font-weight: 700;
  color: #1e293b;
  margin-bottom: 40px;
  line-height: 1.3;
}

.mdtp-xhs-card-content h2 {
  font-size: 56px;
  font-weight: 600;
  color: #334155;
  margin: 50px 0 25px 0;
  line-height: 1.4;
}

.mdtp-xhs-card-content h3 {
  font-size: 48px;
  font-weight: 600;
  color: #475569;
  margin: 40px 0 20px 0;
}

/* 段落 */
.mdtp-xhs-card-content p {
  margin-bottom: 35px;
}

/* 粗体 */
.mdtp-xhs-card-content strong,
.mdtp-xhs-card-content b {
  font-weight: 700;
  color: #1e293b;
}

/* 斜体 */
.mdtp-xhs-card-content em,
.mdtp-xhs-card-content i {
  font-style: italic;
  color: #6366f1;
}

/* 链接 */
.mdtp-xhs-card-content a {
  color: #6366f1;
  text-decoration: none;
  border-bottom: 2px solid #6366f1;
}

/* 列表 */
.mdtp-xhs-card-content ul,
.mdtp-xhs-card-content ol {
  margin: 30px 0;
  padding-left: 60px;
}

.mdtp-xhs-card-content li {
  margin-bottom: 20px;
  line-height: 1.6;
}

/* 引用块 */
.mdtp-xhs-card-content blockquote {
  border-left: 8px solid #6366f1;
  padding-left: 40px;
  background: #f1f5f9;
  padding-top: 25px;
  padding-bottom: 25px;
  padding-right: 30px;
  margin: 35px 0;
  color: #64748b;
  font-style: italic;
  border-radius: 0 12px 12px 0;
}

.mdtp-xhs-card-content blockquote p {
  margin: 0;
}

/* 行内代码 */
.mdtp-xhs-card-content code {
  background: #f1f5f9;
  padding: 6px 16px;
  border-radius: 8px;
  font-family: 'SF Mono', 'Monaco', 'Consolas', monospace;
  font-size: 38px;
  color: #6366f1;
}

/* 代码块 */
.mdtp-xhs-card-content pre {
  background: #1e293b;
  color: #e2e8f0;
  padding: 40px;
  border-radius: 16px;
  margin: 35px 0;
  overflow-x: visible;
  overflow-wrap: break-word;
  word-wrap: break-word;
  word-break: break-all;
  white-space: pre-wrap;
  font-size: 36px;
  line-height: 1.5;
}

.mdtp-xhs-card-content pre code {
  background: transparent;
  color: inherit;
  padding: 0;
  font-size: inherit;
}

/* 图片 */
.mdtp-xhs-card-content img {
  max-width: 100%;
  height: auto;
  border-radius: 16px;
  margin: 35px auto;
  display: block;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
}

/* 分割线 */
.mdtp-xhs-card-content hr {
  border: none;
  height: 2px;
  background: #e2e8f0;
  margin: 50px 0;
}

/* Tags 标签样式 */
.tags-container {
  margin-top: 50px;
  padding-top: 30px;
  border-top: 2px solid #e2e8f0;
}

.tag {
  display: inline-block;
  background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%);
  color: white;
  padding: 12px 28px;
  border-radius: 30px;
  font-size: 34px;
  margin: 10px 15px 10px 0;
  font-weight: 500;
}
`,
	"playful-geometric": `/* ============================================
   Playful Geometric - 活泼几何风格
   Memphis 设计与现代波普艺术的融合
   适配小红书卡片渲染
   ============================================ */

/* 配色定义
   背景色: #FFFDF5 (温暖奶油白 - 纸质感)
   前景色: #1E293B (石板色 800)
   主紫色: #8B5CF6 (Vivid Violet - 品牌主色)
   粉色: #F472B6 (Hot Pink - 俏皮活力)
   黄色: #FBBF24 (Amber/Yellow - 乐观积极)
   薄荷绿: #34D399 (Emerald/Mint - 清新感)
*/

.mdtp-xhs-card-inner {
  background-color: #fffdf5;
  /* 几何点阵背景装饰 */
  background-image: radial-gradient(circle, #e2e8f0 1.5px, transparent 1.5px);
  background-size: 24px 24px;
}

.mdtp-xhs-card-content {
  color: #1e293b;
  font-size: 42px;
  line-height: 1.7;
}

/* 标题样式 */
.mdtp-xhs-card-content h1 {
  font-size: 72px;
  font-weight: 800;
  padding: 0.4em 0.65em;
  background-color: #8b5cf6;
  color: #ffffff;
  border: 3px solid #1e293b;
  border-radius: 0 28px 0 28px;
  box-shadow: 6px 6px 0 #1e293b;
  margin-bottom: 40px;
  line-height: 1.25;
}

.mdtp-xhs-card-content h2 {
  font-size: 56px;
  font-weight: 800;
  padding: 0.3em 0.6em;
  background-color: #fffdf5;
  color: #7c3aed;
  border: 3px solid #1e293b;
  border-left: 10px solid #8b5cf6;
  border-radius: 0 20px 20px 0;
  box-shadow: 5px 5px 0 #f472b6;
  margin: 50px 0 25px 0;
  line-height: 1.25;
}

.mdtp-xhs-card-content h3 {
  font-size: 48px;
  font-weight: 800;
  padding: 0.25em 0.65em;
  color: #1e293b;
  background-color: #fbbf24;
  border: 2px solid #1e293b;
  border-radius: 9999px;
  display: inline-block;
  box-shadow: 4px 4px 0 #1e293b;
  margin: 40px 0 20px 0;
  line-height: 1.25;
}

/* 段落 */
.mdtp-xhs-card-content p {
  margin-bottom: 35px;
}

/* 粗体 - 黄色高亮贴纸效果 */
.mdtp-xhs-card-content strong,
.mdtp-xhs-card-content b {
  font-weight: 700;
  color: #1e293b;
  background-color: #fbbf24;
  padding: 0.1em 0.3em;
  border-radius: 6px;
  box-shadow: 2px 2px 0 rgba(30, 41, 59, 0.2);
}

/* 斜体 - 紫色强调 */
.mdtp-xhs-card-content em,
.mdtp-xhs-card-content i {
  font-style: italic;
  color: #8b5cf6;
  font-weight: 500;
}

/* 链接 - 活泼几何风格 */
.mdtp-xhs-card-content a {
  color: #8b5cf6;
  text-decoration: none;
  font-weight: 500;
  background-color: rgba(139, 92, 246, 0.1);
  padding: 0.08em 0.25em;
  border-radius: 5px;
  border-bottom: 2px solid #8b5cf6;
}

/* 列表 */
.mdtp-xhs-card-content ul,
.mdtp-xhs-card-content ol {
  margin: 30px 0;
  padding-left: 60px;
}

.mdtp-xhs-card-content li {
  margin-bottom: 20px;
  line-height: 1.6;
}

.mdtp-xhs-card-content li::marker {
  color: #8b5cf6;
  font-weight: 700;
}

/* 引用块 - 气泡贴纸风格 */
.mdtp-xhs-card-content blockquote {
  margin: 35px 0;
  padding: 0.8em 1.1em 0.8em 1.6em;
  background-color: #f472b6;
  color: #1e293b;
  border: 3px solid #1e293b;
  border-left: 10px solid #fbbf24;
  border-radius: 0 28px 28px 0;
  box-shadow: 6px 6px 0 #1e293b;
}

.mdtp-xhs-card-content blockquote p {
  margin: 0;
  font-style: normal;
}

/* 行内代码 - 黄色贴纸 */
.mdtp-xhs-card-content code {
  font-family: 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace;
  font-size: 38px;
  background-color: #fbbf24;
  color: #1e293b;
  padding: 0.15em 0.5em;
  border: 2px solid #1e293b;
  border-radius: 8px;
}

/* 代码块 - 深色背景配紫色硬阴影 */
.mdtp-xhs-card-content pre {
  margin: 35px 0;
  padding: 40px;
  background-color: #1e293b;
  border: 3px solid #1e293b;
  border-radius: 20px;
  box-shadow: 8px 8px 0 #8b5cf6;
  overflow-x: visible;
  overflow-wrap: break-word;
  word-wrap: break-word;
  word-break: break-all;
  white-space: pre-wrap;
}

.mdtp-xhs-card-content pre code {
  background-color: transparent;
  color: #ffffff;
  padding: 0;
  border: none;
  border-radius: 0;
  font-size: 36px;
  line-height: 1.55;
}

/* 分割线 - 彩虹几何装饰条 */
.mdtp-xhs-card-content hr {
  margin: 50px 0;
  border: none;
  height: 10px;
  background: repeating-linear-gradient(
    90deg,
    #8b5cf6 0px,
    #8b5cf6 24px,
    #f472b6 24px,
    #f472b6 48px,
    #fbbf24 48px,
    #fbbf24 72px,
    #34d399 72px,
    #34d399 96px
  );
  border-radius: 9999px;
}

/* 图片 - 贴纸框架风格 */
.mdtp-xhs-card-content img {
  display: block;
  max-width: 100%;
  height: auto;
  border: 4px solid #1e293b;
  border-radius: 20px;
  box-shadow: 8px 8px 0 #1e293b;
  margin: 35px auto;
}

/* Tags 标签样式 */
.tags-container {
  margin-top: 50px;
  padding-top: 30px;
  border-top: 5px solid #fbbf24;
}

.tag {
  display: inline-block;
  background-color: #8b5cf6;
  color: white;
  padding: 12px 28px;
  border-radius: 9999px;
  font-size: 34px;
  margin: 10px 15px 10px 0;
  font-weight: 600;
  border: 2px solid #1e293b;
  box-shadow: 3px 3px 0 #1e293b;
}
`,
	"neo-brutalism": `/* ============================================
   Neo-Brutalism - 新粗野主义风格
   RAW. LOUD. UNAPOLOGETIC.
   厚重黑色边框 + 硬阴影 + 高饱和色块
   适配小红书卡片渲染
   ============================================ */

/* 配色定义
   背景色: #FFFDF5 (奶油白)
   主黑色: #000000 (纯黑)
   强调红: #FF4757 (热辣红)
   强调黄: #FECA57 (荧光黄)
   强调青: #00D2D3 (电光青)
   强调紫: #A29BFE (柔和紫)
*/

.mdtp-xhs-card-inner {
  background-color: #fffdf5;
  /* 纸张纹理感 */
  background-image: repeating-linear-gradient(
    0deg,
    transparent,
    transparent 1px,
    rgba(0, 0, 0, 0.008) 1px,
    rgba(0, 0, 0, 0.008) 2px
  );
}

.mdtp-xhs-card-content {
  color: #000000;
  font-size: 42px;
  line-height: 1.7;
}

/* 标题样式 */
.mdtp-xhs-card-content h1 {
  font-size: 72px;
  font-weight: 900;
  padding: 0.4em 0.6em;
  background-color: #feca57;
  color: #000000;
  border: 5px solid #000000;
  box-shadow: 8px 8px 0 #000000;
  text-transform: uppercase;
  margin-bottom: 40px;
  line-height: 1.15;
}

.mdtp-xhs-card-content h2 {
  font-size: 56px;
  font-weight: 900;
  padding: 0.35em 0.6em;
  background-color: #ffffff;
  color: #000000;
  border: 4px solid #000000;
  border-left: 10px solid #ff4757;
  box-shadow: 6px 6px 0 #000000;
  margin: 50px 0 25px 0;
  line-height: 1.15;
}

.mdtp-xhs-card-content h3 {
  font-size: 48px;
  font-weight: 900;
  padding: 0.25em 0.5em;
  color: #000000;
  background-color: #00d2d3;
  border: 4px solid #000000;
  box-shadow: 4px 4px 0 #000000;
  display: inline-block;
  margin: 40px 0 20px 0;
  line-height: 1.15;
}

/* 段落 */
.mdtp-xhs-card-content p {
  margin-bottom: 35px;
}

/* 加粗 - 黄色高亮块 */
.mdtp-xhs-card-content strong,
.mdtp-xhs-card-content b {
  font-weight: 900;
  color: #000000;
  background-color: #feca57;
  padding: 0.08em 0.25em;
  border: 2px solid #000000;
}

/* 斜体 - 红色下划线 */
.mdtp-xhs-card-content em,
.mdtp-xhs-card-content i {
  font-style: italic;
  color: #000000;
  border-bottom: 3px solid #ff4757;
}

/* 链接 - 青色底纹+粗下划线 */
.mdtp-xhs-card-content a {
  color: #000000;
  text-decoration: none;
  background-color: #00d2d3;
  padding: 0.08em 0.2em;
  border-bottom: 4px solid #000000;
  font-weight: 600;
}

/* 列表 */
.mdtp-xhs-card-content ul,
.mdtp-xhs-card-content ol {
  margin: 30px 0;
  padding-left: 60px;
}

.mdtp-xhs-card-content ul {
  list-style-type: square;
}

.mdtp-xhs-card-content li {
  margin-bottom: 20px;
  line-height: 1.6;
}

.mdtp-xhs-card-content li::marker {
  color: #ff4757;
  font-weight: 900;
}

/* 引用块 - 紫色色块+硬阴影 */
.mdtp-xhs-card-content blockquote {
  margin: 35px 0;
  padding: 0.85em 1.1em;
  background-color: #a29bfe;
  color: #000000;
  border: 5px solid #000000;
  border-left: 12px solid #ff4757;
  box-shadow: 8px 8px 0 #000000;
}

.mdtp-xhs-card-content blockquote p {
  margin: 0;
  font-style: normal;
}

/* 行内代码 - 黄色背景 */
.mdtp-xhs-card-content code {
  font-family: 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace;
  font-size: 38px;
  background-color: #feca57;
  color: #000000;
  padding: 0.18em 0.45em;
  border: 3px solid #000000;
  font-weight: 600;
}

/* 代码块 - 黑色背景+红色阴影 */
.mdtp-xhs-card-content pre {
  margin: 35px 0;
  padding: 40px;
  background-color: #000000;
  border: 5px solid #000000;
  box-shadow: 10px 10px 0 #ff4757;
  overflow-x: visible;
  overflow-wrap: break-word;
  word-wrap: break-word;
  word-break: break-all;
  white-space: pre-wrap;
}

.mdtp-xhs-card-content pre code {
  background-color: transparent;
  color: #ffffff;
  padding: 0;
  border: none;
  font-size: 36px;
  line-height: 1.55;
  font-weight: 400;
}

/* 分割线 - 粗犷几何 */
.mdtp-xhs-card-content hr {
  margin: 50px 0;
  border: none;
  height: 8px;
  background-color: #000000;
  box-shadow: 5px 5px 0 #ff4757;
}

/* 图片 - 厚边框框架 */
.mdtp-xhs-card-content img {
  display: block;
  max-width: 100%;
  height: auto;
  border: 5px solid #000000;
  box-shadow: 8px 8px 0 #000000;
  margin: 35px auto;
}

/* Tags 标签样式 */
.tags-container {
  margin-top: 50px;
  padding-top: 30px;
  border-top: 5px solid #000000;
}

.tag {
  display: inline-block;
  background-color: #ff4757;
  color: white;
  padding: 12px 28px;
  font-size: 34px;
  margin: 10px 15px 10px 0;
  font-weight: 800;
  border: 3px solid #000000;
  box-shadow: 4px 4px 0 #000000;
  text-transform: uppercase;
}
`,
	"botanical": `/* ============================================
   Botanical - 植物园风格
   自然柔和，清新淡雅
   适配小红书卡片渲染
   ============================================ */

/* 配色定义
   背景色: #F9FAF6 (淡绿白)
   前景色: #2D3B36 (深绿灰)
   主绿色: #4A7C59 (森林绿)
   浅绿: #8FBC8F (淡绿)
   棕色: #8B7355 (木质棕)
   米色: #E8E4DC (暖米白)
*/

.mdtp-xhs-card-inner {
  background-color: #f9faf6;
}

.mdtp-xhs-card-content {
  color: #2d3b36;
  font-size: 42px;
  line-height: 1.8;
}

/* 标题样式 */
.mdtp-xhs-card-content h1 {
  font-size: 72px;
  font-weight: 700;
  color: #4a7c59;
  margin-bottom: 40px;
  line-height: 1.3;
  padding-bottom: 20px;
  border-bottom: 4px solid #8fbc8f;
}

.mdtp-xhs-card-content h2 {
  font-size: 56px;
  font-weight: 600;
  color: #3d5a48;
  margin: 50px 0 25px 0;
  line-height: 1.4;
  padding-left: 20px;
  border-left: 6px solid #4a7c59;
}

.mdtp-xhs-card-content h3 {
  font-size: 48px;
  font-weight: 600;
  color: #4a7c59;
  margin: 40px 0 20px 0;
}

/* 段落 */
.mdtp-xhs-card-content p {
  margin-bottom: 35px;
}

/* 粗体 */
.mdtp-xhs-card-content strong,
.mdtp-xhs-card-content b {
  font-weight: 700;
  color: #2d3b36;
  background-color: rgba(143, 188, 143, 0.3);
  padding: 0.1em 0.3em;
  border-radius: 4px;
}

/* 斜体 */
.mdtp-xhs-card-content em,
.mdtp-xhs-card-content i {
  font-style: italic;
  color: #4a7c59;
}

/* 链接 */
.mdtp-xhs-card-content a {
  color: #4a7c59;
  text-decoration: none;
  border-bottom: 2px solid #8fbc8f;
  transition: all 0.2s;
}

/* 列表 */
.mdtp-xhs-card-content ul,
.mdtp-xhs-card-content ol {
  margin: 30px 0;
  padding-left: 60px;
}

.mdtp-xhs-card-content li {
  margin-bottom: 20px;
  line-height: 1.6;
}

.mdtp-xhs-card-content li::marker {
  color: #4a7c59;
}

/* 引用块 */
.mdtp-xhs-card-content blockquote {
  margin: 35px 0;
  padding: 30px 40px;
  background-color: #e8e4dc;
  color: #3d5a48;
  border-left: 6px solid #4a7c59;
  border-radius: 0 12px 12px 0;
}

.mdtp-xhs-card-content blockquote p {
  margin: 0;
  font-style: italic;
}

/* 行内代码 */
.mdtp-xhs-card-content code {
  font-family: 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace;
  font-size: 38px;
  background-color: #e8e4dc;
  color: #8b7355;
  padding: 6px 16px;
  border-radius: 6px;
}

/* 代码块 */
.mdtp-xhs-card-content pre {
  margin: 35px 0;
  padding: 40px;
  background-color: #2d3b36;
  color: #e8e4dc;
  border-radius: 12px;
  overflow-x: visible;
  overflow-wrap: break-word;
  word-wrap: break-word;
  word-break: break-all;
  white-space: pre-wrap;
}

.mdtp-xhs-card-content pre code {
  background-color: transparent;
  color: inherit;
  padding: 0;
  font-size: 36px;
  line-height: 1.5;
}

/* 分割线 */
.mdtp-xhs-card-content hr {
  margin: 50px 0;
  border: none;
  height: 3px;
  background: linear-gradient(90deg, transparent, #8fbc8f, transparent);
}

/* 图片 */
.mdtp-xhs-card-content img {
  display: block;
  max-width: 100%;
  height: auto;
  border-radius: 12px;
  margin: 35px auto;
  box-shadow: 0 4px 20px rgba(45, 59, 54, 0.1);
}

/* Tags 标签样式 */
.tags-container {
  margin-top: 50px;
  padding-top: 30px;
  border-top: 2px solid #e8e4dc;
}

.tag {
  display: inline-block;
  background-color: #4a7c59;
  color: white;
  padding: 12px 28px;
  border-radius: 30px;
  font-size: 34px;
  margin: 10px 15px 10px 0;
  font-weight: 500;
}
`,
	"professional": `/* ============================================
   Professional - 专业商务风格
   简洁、稳重、可读性强
   适配小红书卡片渲染
   ============================================ */

/* 配色定义
   背景色: #FFFFFF (纯白)
   前景色: #1A202C (深灰黑)
   主蓝色: #2563EB (专业蓝)
   浅蓝: #DBEAFE (淡蓝背景)
   灰色: #64748B (中性灰)
   边框: #E2E8F0 (浅灰边框)
*/

.mdtp-xhs-card-inner {
  background-color: #ffffff;
}

.mdtp-xhs-card-content {
  color: #1a202c;
  font-size: 42px;
  line-height: 1.75;
}

/* 标题样式 */
.mdtp-xhs-card-content h1 {
  font-size: 72px;
  font-weight: 700;
  color: #1a202c;
  margin-bottom: 40px;
  line-height: 1.3;
  padding-bottom: 20px;
  border-bottom: 3px solid #2563eb;
}

.mdtp-xhs-card-content h2 {
  font-size: 56px;
  font-weight: 600;
  color: #1e40af;
  margin: 50px 0 25px 0;
  line-height: 1.4;
}

.mdtp-xhs-card-content h3 {
  font-size: 48px;
  font-weight: 600;
  color: #374151;
  margin: 40px 0 20px 0;
}

/* 段落 */
.mdtp-xhs-card-content p {
  margin-bottom: 35px;
  color: #374151;
}

/* 粗体 */
.mdtp-xhs-card-content strong,
.mdtp-xhs-card-content b {
  font-weight: 700;
  color: #1a202c;
}

/* 斜体 */
.mdtp-xhs-card-content em,
.mdtp-xhs-card-content i {
  font-style: italic;
  color: #2563eb;
}

/* 链接 */
.mdtp-xhs-card-content a {
  color: #2563eb;
  text-decoration: none;
  border-bottom: 2px solid #93c5fd;
}

/* 列表 */
.mdtp-xhs-card-content ul,
.mdtp-xhs-card-content ol {
  margin: 30px 0;
  padding-left: 60px;
}

.mdtp-xhs-card-content li {
  margin-bottom: 20px;
  line-height: 1.6;
  color: #374151;
}

.mdtp-xhs-card-content li::marker {
  color: #2563eb;
}

/* 引用块 */
.mdtp-xhs-card-content blockquote {
  margin: 35px 0;
  padding: 30px 40px;
  background-color: #dbeafe;
  color: #1e40af;
  border-left: 5px solid #2563eb;
  border-radius: 0 8px 8px 0;
}

.mdtp-xhs-card-content blockquote p {
  margin: 0;
}

/* 行内代码 */
.mdtp-xhs-card-content code {
  font-family: 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace;
  font-size: 38px;
  background-color: #f1f5f9;
  color: #0f172a;
  padding: 6px 16px;
  border-radius: 6px;
}

/* 代码块 */
.mdtp-xhs-card-content pre {
  margin: 35px 0;
  padding: 40px;
  background-color: #0f172a;
  color: #e2e8f0;
  border-radius: 12px;
  overflow-x: visible;
  overflow-wrap: break-word;
  word-wrap: break-word;
  word-break: break-all;
  white-space: pre-wrap;
}

.mdtp-xhs-card-content pre code {
  background-color: transparent;
  color: inherit;
  padding: 0;
  font-size: 36px;
  line-height: 1.5;
}

/* 分割线 */
.mdtp-xhs-card-content hr {
  margin: 50px 0;
  border: none;
  height: 2px;
  background-color: #e2e8f0;
}

/* 图片 */
.mdtp-xhs-card-content img {
  display: block;
  max-width: 100%;
  height: auto;
  border-radius: 8px;
  margin: 35px auto;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
}

/* Tags 标签样式 */
.tags-container {
  margin-top: 50px;
  padding-top: 30px;
  border-top: 2px solid #e2e8f0;
}

.tag {
  display: inline-block;
  background-color: #2563eb;
  color: white;
  padding: 12px 28px;
  border-radius: 6px;
  font-size: 34px;
  margin: 10px 15px 10px 0;
  font-weight: 500;
}
`,
	"retro": `/* ============================================
   Retro - 复古怀旧风格
   温暖的米色调和复古排版
   适配小红书卡片渲染
   ============================================ */

/* 配色定义
   背景色: #FDF6E3 (复古米黄)
   前景色: #5C4033 (棕褐色)
   主色: #D35400 (复古橙)
   浅橙: #F39C12 (暖黄)
   深棕: #8B4513 (马鞍棕)
   米色: #F5DEB3 (小麦色)
*/

.mdtp-xhs-card-inner {
  background-color: #fdf6e3;
}

.mdtp-xhs-card-content {
  color: #5c4033;
  font-size: 42px;
  line-height: 1.8;
}

/* 标题样式 */
.mdtp-xhs-card-content h1 {
  font-size: 72px;
  font-weight: 700;
  color: #d35400;
  margin-bottom: 40px;
  line-height: 1.3;
  border-bottom: 4px double #d35400;
  padding-bottom: 15px;
}

.mdtp-xhs-card-content h2 {
  font-size: 56px;
  font-weight: 600;
  color: #8b4513;
  margin: 50px 0 25px 0;
  line-height: 1.4;
}

.mdtp-xhs-card-content h3 {
  font-size: 48px;
  font-weight: 600;
  color: #a0522d;
  margin: 40px 0 20px 0;
  font-style: italic;
}

/* 段落 */
.mdtp-xhs-card-content p {
  margin-bottom: 35px;
}

/* 粗体 */
.mdtp-xhs-card-content strong,
.mdtp-xhs-card-content b {
  font-weight: 700;
  color: #8b4513;
}

/* 斜体 */
.mdtp-xhs-card-content em,
.mdtp-xhs-card-content i {
  font-style: italic;
  color: #d35400;
}

/* 链接 */
.mdtp-xhs-card-content a {
  color: #d35400;
  text-decoration: underline;
  text-decoration-style: wavy;
  text-underline-offset: 4px;
}

/* 列表 */
.mdtp-xhs-card-content ul,
.mdtp-xhs-card-content ol {
  margin: 30px 0;
  padding-left: 60px;
}

.mdtp-xhs-card-content li {
  margin-bottom: 20px;
  line-height: 1.6;
}

.mdtp-xhs-card-content li::marker {
  color: #d35400;
}

/* 引用块 */
.mdtp-xhs-card-content blockquote {
  margin: 35px 0;
  padding: 30px 40px;
  background-color: #f5deb3;
  color: #5c4033;
  border-left: 6px solid #d35400;
  font-style: italic;
}

.mdtp-xhs-card-content blockquote p {
  margin: 0;
}

/* 行内代码 */
.mdtp-xhs-card-content code {
  font-family: 'Courier New', Courier, monospace;
  font-size: 38px;
  background-color: #f5deb3;
  color: #8b4513;
  padding: 6px 16px;
  border-radius: 4px;
}

/* 代码块 */
.mdtp-xhs-card-content pre {
  margin: 35px 0;
  padding: 40px;
  background-color: #5c4033;
  color: #fdf6e3;
  border: 3px solid #8b4513;
  overflow-x: visible;
  overflow-wrap: break-word;
  word-wrap: break-word;
  word-break: break-all;
  white-space: pre-wrap;
}

.mdtp-xhs-card-content pre code {
  background-color: transparent;
  color: inherit;
  padding: 0;
  font-size: 36px;
  line-height: 1.5;
}

/* 分割线 */
.mdtp-xhs-card-content hr {
  margin: 50px 0;
  border: none;
  height: 3px;
  background: repeating-linear-gradient(
    90deg,
    #d35400,
    #d35400 10px,
    transparent 10px,
    transparent 20px
  );
}

/* 图片 */
.mdtp-xhs-card-content img {
  display: block;
  max-width: 100%;
  height: auto;
  margin: 35px auto;
  border: 4px solid #8b4513;
  box-shadow: 4px 4px 0 #d35400;
}

/* Tags 标签样式 */
.tags-container {
  margin-top: 50px;
  padding-top: 30px;
  border-top: 3px double #d35400;
}

.tag {
  display: inline-block;
  background-color: #d35400;
  color: #fdf6e3;
  padding: 12px 28px;
  border-radius: 4px;
  font-size: 34px;
  margin: 10px 15px 10px 0;
  font-weight: 600;
  border: 2px solid #8b4513;
}
`,
	"terminal": `/* ============================================
   Terminal - 终端/命令行风格
   黑客美学，极简科技感
   适配小红书卡片渲染
   ============================================ */

/* 配色定义
   背景色: #0D1117 (深黑)
   前景色: #C9D1D9 (淡灰白)
   主绿: #39D353 (终端绿)
   黄色: #F0E68C (警告黄)
   青色: #58A6FF (链接蓝)
   紫色: #A371F7 (高亮紫)
*/

.mdtp-xhs-card-inner {
  background-color: #0d1117;
}

.mdtp-xhs-card-content {
  color: #c9d1d9;
  font-family: 'SF Mono', 'Monaco', 'Consolas', 'Liberation Mono', monospace;
  font-size: 40px;
  line-height: 1.6;
}

/* 标题样式 */
.mdtp-xhs-card-content h1 {
  font-size: 68px;
  font-weight: 700;
  color: #39d353;
  margin-bottom: 40px;
  line-height: 1.3;
}

.mdtp-xhs-card-content h1::before {
  content: '# ';
  color: #58a6ff;
}

.mdtp-xhs-card-content h2 {
  font-size: 54px;
  font-weight: 600;
  color: #58a6ff;
  margin: 50px 0 25px 0;
  line-height: 1.4;
}

.mdtp-xhs-card-content h2::before {
  content: '## ';
  color: #a371f7;
}

.mdtp-xhs-card-content h3 {
  font-size: 46px;
  font-weight: 600;
  color: #a371f7;
  margin: 40px 0 20px 0;
}

.mdtp-xhs-card-content h3::before {
  content: '### ';
  color: #39d353;
}

/* 段落 */
.mdtp-xhs-card-content p {
  margin-bottom: 35px;
}

/* 粗体 */
.mdtp-xhs-card-content strong,
.mdtp-xhs-card-content b {
  font-weight: 700;
  color: #39d353;
}

/* 斜体 */
.mdtp-xhs-card-content em,
.mdtp-xhs-card-content i {
  font-style: italic;
  color: #f0e68c;
}

/* 链接 */
.mdtp-xhs-card-content a {
  color: #58a6ff;
  text-decoration: underline;
  text-underline-offset: 4px;
}

/* 列表 */
.mdtp-xhs-card-content ul,
.mdtp-xhs-card-content ol {
  margin: 30px 0;
  padding-left: 60px;
}

.mdtp-xhs-card-content li {
  margin-bottom: 20px;
  line-height: 1.6;
}

.mdtp-xhs-card-content li::marker {
  color: #39d353;
}

/* 引用块 */
.mdtp-xhs-card-content blockquote {
  margin: 35px 0;
  padding: 30px 40px;
  background-color: #161b22;
  color: #8b949e;
  border-left: 4px solid #39d353;
}

.mdtp-xhs-card-content blockquote::before {
  content: '> ';
  color: #39d353;
}

.mdtp-xhs-card-content blockquote p {
  margin: 0;
}

/* 行内代码 */
.mdtp-xhs-card-content code {
  font-family: inherit;
  font-size: 38px;
  background-color: #21262d;
  color: #f0e68c;
  padding: 6px 16px;
  border-radius: 6px;
}

/* 代码块 */
.mdtp-xhs-card-content pre {
  margin: 35px 0;
  padding: 40px;
  background-color: #161b22;
  color: #c9d1d9;
  border: 1px solid #30363d;
  border-radius: 8px;
  overflow-x: visible;
  overflow-wrap: break-word;
  word-wrap: break-word;
  word-break: break-all;
  white-space: pre-wrap;
}

.mdtp-xhs-card-content pre code {
  background-color: transparent;
  color: inherit;
  padding: 0;
  font-size: 36px;
  line-height: 1.5;
}

/* 分割线 */
.mdtp-xhs-card-content hr {
  margin: 50px 0;
  border: none;
  height: 2px;
  background-color: #30363d;
}

/* 图片 */
.mdtp-xhs-card-content img {
  display: block;
  max-width: 100%;
  height: auto;
  margin: 35px auto;
  border: 1px solid #30363d;
  border-radius: 8px;
}

/* Tags 标签样式 */
.tags-container {
  margin-top: 50px;
  padding-top: 30px;
  border-top: 1px solid #30363d;
}

.tag {
  display: inline-block;
  background-color: #21262d;
  color: #39d353;
  padding: 12px 28px;
  border-radius: 30px;
  font-size: 32px;
  margin: 10px 15px 10px 0;
  font-weight: 500;
  border: 1px solid #39d353;
}
`,
	"sketch": `/* ============================================
   Sketch - 手绘素描风格
   纸张质感、手写字体效果
   适配小红书卡片渲染
   ============================================ */

/* 配色定义
   背景色: #FFFEF9 (米白纸张)
   前景色: #333333 (炭笔黑)
   主色: #555555 (铅笔灰)
   强调: #E74C3C (红色标记笔)
   蓝色: #3498DB (蓝色圆珠笔)
   黄色: #F1C40F (荧光笔)
*/

.mdtp-xhs-card-inner {
  background-color: #fffef9;
  /* 纸张网格背景 */
  background-image: 
    linear-gradient(#e0e0e0 1px, transparent 1px),
    linear-gradient(90deg, #e0e0e0 1px, transparent 1px);
  background-size: 30px 30px;
}

.mdtp-xhs-card-content {
  color: #333333;
  font-size: 42px;
  line-height: 1.8;
}

/* 标题样式 */
.mdtp-xhs-card-content h1 {
  font-size: 72px;
  font-weight: 700;
  color: #333333;
  margin-bottom: 40px;
  line-height: 1.3;
  text-decoration: underline;
  text-decoration-style: wavy;
  text-decoration-color: #e74c3c;
  text-underline-offset: 10px;
}

.mdtp-xhs-card-content h2 {
  font-size: 56px;
  font-weight: 600;
  color: #555555;
  margin: 50px 0 25px 0;
  line-height: 1.4;
  border-bottom: 3px dashed #999999;
  padding-bottom: 10px;
}

.mdtp-xhs-card-content h3 {
  font-size: 48px;
  font-weight: 600;
  color: #666666;
  margin: 40px 0 20px 0;
}

/* 段落 */
.mdtp-xhs-card-content p {
  margin-bottom: 35px;
}

/* 粗体 - 加粗圈标 */
.mdtp-xhs-card-content strong,
.mdtp-xhs-card-content b {
  font-weight: 700;
  color: #333333;
  background-color: #f1c40f;
  padding: 0.1em 0.3em;
  border-radius: 4px;
}

/* 斜体 */
.mdtp-xhs-card-content em,
.mdtp-xhs-card-content i {
  font-style: italic;
  color: #3498db;
}

/* 链接 */
.mdtp-xhs-card-content a {
  color: #3498db;
  text-decoration: underline;
  text-decoration-style: dashed;
}

/* 列表 */
.mdtp-xhs-card-content ul,
.mdtp-xhs-card-content ol {
  margin: 30px 0;
  padding-left: 60px;
}

.mdtp-xhs-card-content li {
  margin-bottom: 20px;
  line-height: 1.6;
}

.mdtp-xhs-card-content li::marker {
  color: #e74c3c;
}

/* 引用块 - 便签纸风格 */
.mdtp-xhs-card-content blockquote {
  margin: 35px 0;
  padding: 30px 40px;
  background-color: #fff9c4;
  color: #333333;
  border: none;
  box-shadow: 3px 3px 0 #ddd;
  transform: rotate(-0.5deg);
}

.mdtp-xhs-card-content blockquote p {
  margin: 0;
  font-style: italic;
}

/* 行内代码 */
.mdtp-xhs-card-content code {
  font-family: 'Courier New', Courier, monospace;
  font-size: 38px;
  background-color: #f0f0f0;
  color: #555555;
  padding: 6px 16px;
  border: 2px dashed #999999;
  border-radius: 4px;
}

/* 代码块 */
.mdtp-xhs-card-content pre {
  margin: 35px 0;
  padding: 40px;
  background-color: #f5f5f5;
  color: #333333;
  border: 2px solid #333333;
  overflow-x: visible;
  overflow-wrap: break-word;
  word-wrap: break-word;
  word-break: break-all;
  white-space: pre-wrap;
}

.mdtp-xhs-card-content pre code {
  background-color: transparent;
  color: inherit;
  padding: 0;
  border: none;
  font-size: 36px;
  line-height: 1.5;
}

/* 分割线 */
.mdtp-xhs-card-content hr {
  margin: 50px 0;
  border: none;
  height: 3px;
  background: repeating-linear-gradient(
    90deg,
    #333333,
    #333333 5px,
    transparent 5px,
    transparent 10px
  );
}

/* 图片 */
.mdtp-xhs-card-content img {
  display: block;
  max-width: 100%;
  height: auto;
  margin: 35px auto;
  border: 3px solid #333333;
  box-shadow: 5px 5px 0 #ddd;
  transform: rotate(0.5deg);
}

/* Tags 标签样式 */
.tags-container {
  margin-top: 50px;
  padding-top: 30px;
  border-top: 2px dashed #999999;
}

.tag {
  display: inline-block;
  background-color: #fff;
  color: #333333;
  padding: 12px 28px;
  border: 2px solid #333333;
  font-size: 34px;
  margin: 10px 15px 10px 0;
  font-weight: 600;
  transform: rotate(-1deg);
}
`,
};
